blank_issues_enabled: false
contact_links:
  - name: Read our documentations
    url: https://dbeaver.com/docs/cloudbeaver
    about: Many articles about product deployment and features.
  - name: Try advanced database management features in DBeaver PRO or CloudBeaver EE
    url: https://dbeaver.com/download/?utm_source=github&utm_medium=social&utm_campaign=issue
    about: Download a 14-day free trial on dbeaver.com. No credit card is needed.
  - name: Learn how to use CloudBeaver effectively with our tutorial videos
    url: https://www.youtube.com/channel/UC-yOjsQLSaJVEghg6UB3N7A
    about: Subscribe to our YouTube channel and watch new tutorials every week.
  - name: Follow us on X (ex. Twitter)
    url: https://x.com/dbeaver_news
    about: Get everyday tips, fresh news, and DBeaver/CloudBeaver feature overviews.
